service: rsp-cpms-checking

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "sqs:SendMessage"
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
        - "sqs:GetQueueAttributes"
      Resource: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:CPMS_Launched_Payments

# custom:
#   initialWait: 1
#   maxAttempts: 4

functions:
  checkForOrphanedPayments:
    handler: handler.checkForOrphanedPayments
    events:
      - sqs:
          arn: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:LaunchedPayments

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

resources:
  Resources:
    LaunchedPayments:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "LaunchedPayments"
        RedrivePolicy:
          deadLetterTargetArn: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:DeadLetterLaunchedPayments
          maxReceiveCount: 4
    DeadLetterLaunchedPayments:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "DeadLetterLaunchedPayments"